name: flexischool
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  connectivity_plus: ^4.0.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.0
  intl: any
  file_picker: ^5.3.2
  gallery_saver: ^2.3.2
  top_snackbar_flutter: ^3.1.0
  path_provider: ^2.0.15
  open_file: ^3.3.2
  permission_handler: ^10.4.3
  awesome_notifications: ^0.7.4+1
  syncfusion_flutter_calendar: ^22.1.39
  flutter_multiselect: ^1.0.0
  multi_select_flutter: ^4.1.3
  search_choices: ^2.2.5
  table_calendar: ^3.0.9
  flutter_quill: ^7.3.0
  quill_json_to_html: ^1.0.1
  flutter_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/home.jpg
    - assets/images/top_header.png
    - assets/images/
  fonts:
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/mo_me.ttf

    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/mo_re.ttf
