// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnH8_XKS8a7ARcVM9v5Ll3Ac2AMM6dOL0',
    appId: '1:905905139189:android:4d843074e1c0e0fb92c4bc',
    messagingSenderId: '905905139189',
    projectId: 'flexischoolapp',
    storageBucket: 'flexischoolapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8jcuL62IfqTOfMobekbKYKsyiP4IQk34',
    appId: '1:905905139189:ios:0888104f7da0b23092c4bc',
    messagingSenderId: '905905139189',
    projectId: 'flexischoolapp',
    storageBucket: 'flexischoolapp.appspot.com',
    androidClientId: '905905139189-u2o0m3sbdbr0ug8abf88lvkdjsdi38co.apps.googleusercontent.com',
    iosClientId: '905905139189-o75qt6kplv2j033mvp7lfa3jfd9vq4ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexischool',
  );
}
